//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoOnePiece.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Crew {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Crew() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessWhoOnePiece.Model.Resources.Crew", typeof(Crew).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage du On-Air.
        /// </summary>
        internal static string ApooCrew {
            get {
                return ResourceManager.GetString("ApooCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage d&apos;Arlong.
        /// </summary>
        internal static string ArlongCrew {
            get {
                return ResourceManager.GetString("ArlongCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assassin.
        /// </summary>
        internal static string Assassin {
            get {
                return ResourceManager.GetString("Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bandit.
        /// </summary>
        internal static string Bandit {
            get {
                return ResourceManager.GetString("Bandit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baroque Works.
        /// </summary>
        internal static string BaroqueWorks {
            get {
                return ResourceManager.GetString("BaroqueWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage du Fire Tank.
        /// </summary>
        internal static string BegeCrew {
            get {
                return ResourceManager.GetString("BegeCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Big Mom.
        /// </summary>
        internal static string BigMomCrew {
            get {
                return ResourceManager.GetString("BigMomCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage du Chat Noir.
        /// </summary>
        internal static string BlackCatCrew {
            get {
                return ResourceManager.GetString("BlackCatCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Bluejam.
        /// </summary>
        internal static string BluejamCrew {
            get {
                return ResourceManager.GetString("BluejamCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Bonney.
        /// </summary>
        internal static string BonneyCrew {
            get {
                return ResourceManager.GetString("BonneyCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Caribou.
        /// </summary>
        internal static string CaribouCrew {
            get {
                return ResourceManager.GetString("CaribouCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Celestial Dragons.
        /// </summary>
        internal static string CelestialDragons {
            get {
                return ResourceManager.GetString("CelestialDragons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cinq Doyens.
        /// </summary>
        internal static string CinqDoyens {
            get {
                return ResourceManager.GetString("CinqDoyens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cipher Pol.
        /// </summary>
        internal static string CipherPol {
            get {
                return ResourceManager.GetString("CipherPol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Citizen.
        /// </summary>
        internal static string Citizen {
            get {
                return ResourceManager.GetString("Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cross Guild.
        /// </summary>
        internal static string CrossGuild {
            get {
                return ResourceManager.GetString("CrossGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Don Quichotte Doflamingo.
        /// </summary>
        internal static string DoflamingoCrew {
            get {
                return ResourceManager.GetString("DoflamingoCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Armada Pirate de Don Krieg.
        /// </summary>
        internal static string DonKriegCrew {
            get {
                return ResourceManager.GetString("DonKriegCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clan d&apos;Ener.
        /// </summary>
        internal static string EnerCrew {
            get {
                return ResourceManager.GetString("EnerCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faux Équipage du Chapeau de Paille.
        /// </summary>
        internal static string FalseMugiwaraCrew {
            get {
                return ResourceManager.GetString("FalseMugiwaraCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Foxy.
        /// </summary>
        internal static string FoxyCrew {
            get {
                return ResourceManager.GetString("FoxyCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage des Géants.
        /// </summary>
        internal static string GiantsCrew {
            get {
                return ResourceManager.GetString("GiantsCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gouvernement Mondial.
        /// </summary>
        internal static string GouvernementMondial {
            get {
                return ResourceManager.GetString("GouvernementMondial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Hawkins.
        /// </summary>
        internal static string HawkinsCrew {
            get {
                return ResourceManager.GetString("HawkinsCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impel Down.
        /// </summary>
        internal static string ImpelDown {
            get {
                return ResourceManager.GetString("ImpelDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage aux Cent Bêtes.
        /// </summary>
        internal static string KaidoCrew {
            get {
                return ResourceManager.GetString("KaidoCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Kid.
        /// </summary>
        internal static string KidCrew {
            get {
                return ResourceManager.GetString("KidCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kujas.
        /// </summary>
        internal static string Kujas {
            get {
                return ResourceManager.GetString("Kujas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage du Heart.
        /// </summary>
        internal static string LawCrew {
            get {
                return ResourceManager.GetString("LawCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bandits des montagnes.
        /// </summary>
        internal static string MountainBandit {
            get {
                return ResourceManager.GetString("MountainBandit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allié de L&apos;Équipage du Chapeau de Paille.
        /// </summary>
        internal static string MugiwaraAllies {
            get {
                return ResourceManager.GetString("MugiwaraAllies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage du Chapeau de Paille.
        /// </summary>
        internal static string MugiwaraCrew {
            get {
                return ResourceManager.GetString("MugiwaraCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Navy&apos;s Crew.
        /// </summary>
        internal static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Néo Mads.
        /// </summary>
        internal static string NeoMads {
            get {
                return ResourceManager.GetString("NeoMads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Comer Land.
        /// </summary>
        internal static string NewComerLand {
            get {
                return ResourceManager.GetString("NewComerLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage des Nouveaux Hommes-Poissons.
        /// </summary>
        internal static string NewFishmenCrew {
            get {
                return ResourceManager.GetString("NewFishmenCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Barbe Blanche.
        /// </summary>
        internal static string NewgateCrew {
            get {
                return ResourceManager.GetString("NewgateCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pirate.
        /// </summary>
        internal static string Pirate {
            get {
                return ResourceManager.GetString("Pirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ligue des Primates.
        /// </summary>
        internal static string PrimatesCrew {
            get {
                return ResourceManager.GetString("PrimatesCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revolutionary&apos;s Army.
        /// </summary>
        internal static string RevolutionaryArmy {
            get {
                return ResourceManager.GetString("RevolutionaryArmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage des Pirates de Roger.
        /// </summary>
        internal static string RogerCrew {
            get {
                return ResourceManager.GetString("RogerCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage du Rolling.
        /// </summary>
        internal static string RollingCrew {
            get {
                return ResourceManager.GetString("RollingCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seraphim.
        /// </summary>
        internal static string Seraphim {
            get {
                return ResourceManager.GetString("Seraphim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage du Roux.
        /// </summary>
        internal static string ShanksCrew {
            get {
                return ResourceManager.GetString("ShanksCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage du Lion d&apos;Or.
        /// </summary>
        internal static string ShikiCrew {
            get {
                return ResourceManager.GetString("ShikiCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage des Pirates du Soleil.
        /// </summary>
        internal static string SunPiratesCrew {
            get {
                return ResourceManager.GetString("SunPiratesCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Barbe Noire.
        /// </summary>
        internal static string TeachCrew {
            get {
                return ResourceManager.GetString("TeachCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thriller Bark.
        /// </summary>
        internal static string ThrillerBark {
            get {
                return ResourceManager.GetString("ThrillerBark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage des Moines Dépravés.
        /// </summary>
        internal static string UrougeCrew {
            get {
                return ResourceManager.GetString("UrougeCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L’Équipage de Wapol.
        /// </summary>
        internal static string WapolCrew {
            get {
                return ResourceManager.GetString("WapolCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edward Weeble.
        /// </summary>
        internal static string WeebleCrew {
            get {
                return ResourceManager.GetString("WeebleCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zo.
        /// </summary>
        internal static string ZoCrew {
            get {
                return ResourceManager.GetString("ZoCrew", resourceCulture);
            }
        }
    }
}
