//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoOnePiece.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessWhoOnePiece.Model.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allié de L&apos;Équipage du Chapeau de Paille.
        /// </summary>
        internal static string AlliedMugiwaraCrew {
            get {
                return ResourceManager.GetString("AlliedMugiwaraCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Baroque Works.
        /// </summary>
        internal static string BaroqueWorks {
            get {
                return ResourceManager.GetString("BaroqueWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Big Mom.
        /// </summary>
        internal static string BigMomCrew {
            get {
                return ResourceManager.GetString("BigMomCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Celestial Dragons.
        /// </summary>
        internal static string CelestialDragons {
            get {
                return ResourceManager.GetString("CelestialDragons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Citizen.
        /// </summary>
        internal static string Citizen {
            get {
                return ResourceManager.GetString("Citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cross Guild.
        /// </summary>
        internal static string CrossGuild {
            get {
                return ResourceManager.GetString("CrossGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;Équipage de Don Quichotte Doflamingo.
        /// </summary>
        internal static string DoffyFamily {
            get {
                return ResourceManager.GetString("DoffyFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Navy&apos;s Crew.
        /// </summary>
        internal static string NavyCrew {
            get {
                return ResourceManager.GetString("NavyCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Navy.
        /// </summary>
        internal static string NavyType {
            get {
                return ResourceManager.GetString("NavyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pirate.
        /// </summary>
        internal static string PirateType {
            get {
                return ResourceManager.GetString("PirateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revolutionary&apos;s Army.
        /// </summary>
        internal static string RevolutionaryCrew {
            get {
                return ResourceManager.GetString("RevolutionaryCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Revolutionary.
        /// </summary>
        internal static string RevolutionaryType {
            get {
                return ResourceManager.GetString("RevolutionaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;équipage de Barbe Noire.
        /// </summary>
        internal static string TeachCrew {
            get {
                return ResourceManager.GetString("TeachCrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thriller Bark.
        /// </summary>
        internal static string ThrillerBark {
            get {
                return ResourceManager.GetString("ThrillerBark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
